### ISSUE TITLE
Unable to set taken_at with post photos

### ISSUE THREAD

**Issue by HayoBaan** [500px/api-documentation#105]
In my application I would like the user to be able to specify the date at which the image was taken (e.g., to override the value in exif). This currently doesn't seem to be possible with "post photos"; it always sets the taken_at to null.
Can you offer me a solution?

**Comment by cdmicacc** [comment]
Interesting.  It seems that while you can *update* a photo to change it's `taken_at`, you can't actually set the value when you create it (except via EXIF data).  I've created a ticket for this issue and make a quick fix.  I'll update you here when the fix has been deployed.

**Comment by Melraidin** [comment]
@HayoBaan This fix has been deployed. Please let us know if you run into any further issues.

**Comment by HayoBaan** [comment]
Hi @Melraidin, excellent! Thanks I tested it and it works. I just have a question regarding the timezone. It seems to (always) go to -05:00 even if I specify it as in "01/02/2003 14:15:16+01:00"
Am I doing something wrong (e.g., wrong format?), or is there something else at play here?
