### ISSUE TITLE
Photos from a period of time

### ISSUE THREAD

**Issue by phpexp1** [500px/api-documentation#106]
Hi,

Thanks a lot for the 500px API. Is there any way to query photos from a period of time?
For example: I need all the photos from a certain area created in this month, .

Thanks,
Michal

**Comment by cdmicacc** [comment]
@vachi is correct - we currently don't expose a way to restrict search results to a specific block of time.  However, if you want the most recent (or least recent) photos for a search, you can order the results by `created_at`.
