### ISSUE TITLE
Fresh today featured - uploading using API

### ISSUE THREAD

**Issue by Cmejia** [500px/api-documentation#111]
It seems that photos uploaded using the API, and metadata modifications using the API, do not trigger the criteria that puts the photo in "Fresh today"

We have an app (out in the market for a few years) that uploads.  Even if you meet the criteria (caption, category, tags), the photo is not put in "Fresh today".  Editing the photo's metadata, like adding a tag, also does not help. 

The only way is to go 500px.com website and make a change there or through the official app. Is there something we're missing ?

**Comment by cdmicacc** [comment]
This should work (assuming the photo is also public -- I assume that's the case?).  

Can you post the API requests you're sending here, so I can take a look?

**Comment by Cmejia** [comment]
Yes, this is the sequence of calls when we upload a new photo. I've masked the oauth keys, and did not include the image binary data.  The calls themselves are all successful, photo is uploaded, tags, category, caption and location are set properly. it just does not go to "Fresh today"

POST https://api.500px.com/v1/photos
longitude=-99.19656111111111&privacy=0&latitude=19.42975277777778&name=Neveria%20Roxy&description=Ice%20cream%20parlour&category=5

====================================================================
POST http://upload.500px.com/api/v1/upload
65AB6FBB-FF9A-4B7C-BB9F-9ECEF618F22E-150
Content-Disposition: form-data; name="photo_id"

95159693
--65AB6FBB-FF9A-4B7C-BB9F-9ECEF618F22E-150
Content-Disposition: form-data; name="upload_key"

xxxxxxxxxxxx
--65AB6FBB-FF9A-4B7C-BB9F-9ECEF618F22E-150
Content-Disposition: form-data; name="consumer_key"

xxxxxxxxxxxxx
--65AB6FBB-FF9A-4B7C-BB9F-9ECEF618F22E-150
Content-Disposition: form-data; name="access_key"

YtgE1nlxgrMa05LrZyeJ63klcvW9iMSukyOs17Hk
--65AB6FBB-FF9A-4B7C-BB9F-9ECEF618F22E-150
Content-Disposition: form-data; name="file"; filename="Neveria%20Roxy"
Content-Type: image/jpeg

====================================================================
POST https://api.500px.com/v1/photos/95159693/tags
tags=icecream%2Chelado%2Cmexico

**Comment by Cmejia** [comment]
any news ? :)

**Comment by vachi** [comment]
u guess its the holidays...

**Comment by gregr** [comment]
Thanks for the helpful request sequence, Carlos.  We're digging into this.

**Comment by gregr** [comment]
Hi Carlos,

Can you attempt your sequence again and let me know whether it works?  We
pushed a change earlier that should address the issue you were seeing.

Thanks!

**Comment by Cmejia** [comment]
Hi Greg, 
I've just tested this and it works beautifully now.  If the photo meets the criteria (title, 3+ tags and category), then it shows in 'Fresh Today' right away, no changes needed on our app. 

Thank you !
