### ISSUE TITLE
Retrieve pictures by set

### ISSUE THREAD

**Issue by icechen1** [500px/api-documentation#115]
Hi!

I'm trying to make a slideshow on my website that loads a picture set on my account exclusively.

Right now I am calling the following in order to retrieve all images on my account:
_500px.api('/photos', { feature: 'user', username: "yuchenhou",image_size:5 }

However, I am wondering if it's possible to modify the query to only return pictures from a specific picture set?

Thanks!

**Comment by cdmicacc** [comment]
See the Collections API: https://github.com/500px/api-documentation/blob/master/endpoints/collections/GET_collections_id.md

**Comment by icechen1** [comment]
Hi, thank you for the quick response!

The Collections API seems to require me to be authenticated to my account. Is there a way to retrieve a public set on my profile without going through OAuth auth? Like with /photos/ where I only need to supply my API key in order to retrieve every picture on my account.
