### ISSUE TITLE
Get images sizes from collection results

### ISSUE THREAD

**Issue by jenius** [500px/api-documentation#122]
Just a quick questions and/or request:

When you get a collection, it returns all the photo objects inside of it -- currently it only returns the `2` size, which is a tiny thumbnail. I know you can use `image_size` to get back different sizes for specific photos, is there any way to specify the `image_size` that the collection will return for all photos?

**Comment by cdmicacc** [comment]
Yes, you can include `image_size=3` to get, say, size 3, or `image_size[]=2&image_size[]=3` to get both sizes 2 and 3.

**Comment by jenius** [comment]
Thank you!
