### ISSUE TITLE
Getting images from collections just stopped working

### ISSUE THREAD

**Issue by gryphon** [500px/api-documentation#123]
Everything was working well for 2 years but getting collection photos just stopped working now.
Please check:
http://homich.ru/category/photos/

Collection photos list is working well but when browser making request to image_url it gets "Unauthorized" response.

**Comment by Melraidin** [comment]
It looks like you're modifying the URLs being returned by the API. These must be treated as opaque identifiers - you should not change their values before making a request.

If you want to get a different image size from the API you may specify the ```image_size``` parameter.

To get size 4 add ```image_size=4``` to your request.

To get both sizes 3 and 4: ```image_size[]=3&image_size[]=4```

**Comment by gryphon** [comment]
Yes it seems to be so. I will try, thank you!
