### ISSUE TITLE
Image url returned by API call contains escape sequence

### ISSUE THREAD

**Issue by cvezina** [500px/api-documentation#127]
Hi,

I have developed an app that is using 500px API. Since yesterday, people using my app are reporting problems saying that they can't open url because of an error.

After investigating, i found that the url provided by 500px API includes escape sequences while it doesn't in the pass.

For example, the url below include %3D escape sequence while it doesn't before:

https://drscdn.500px.org/photo/102262127/m%3D900/efafc0b2e44847fdd82b029a052fab67

In my code, I am automatically add url escape sequences so I get the new url below:

https://drscdn.500px.org/photo/102262127/m%253D900/efafc0b2e44847fdd82b029a052fab67

As you can see, %25 is added in front of 3D creating a bas url.

Is there a reason why 500px API is providing url that includes escape sequences?

Thanks,

Claude Vezina
PCV

**Comment by cdmicacc** [comment]
We escape certain characters because some HTTP clients incorrectly handle parsing of URLs where they occur in the path segment.  You should change your code to stop escaping the URL a second time.
