### ISSUE TITLE
Serach Picture by KeyWords

### ISSUE THREAD

**Issue by yruama** [500px/api-documentation#131]
Hi.

How can i search pitcure by Keyword with Javascript SDK ?

I try this : _500px.api('/photos', {term: 'sun'}, function(photos) but it does not work

**Comment by cdmicacc** [comment]
You probably want to use the [search API call](https://github.com/500px/api-documentation/blob/master/endpoints/photo/GET_photos_search.md) which accepts a `tag` parameter.
