### ISSUE TITLE
Removing favourites

### ISSUE THREAD

**Issue by shiyunhe** [500px/api-documentation#132]
One of my iOS app users is reporting a favourites removing issue.

If more than 10 favourites are being removed continuously, API calls stop responding after 5 - 10 calls
The account will get locked out for 10 - 20 minutes before the app can do anything. From my experiments, it looks like that the locking is based on publicly visible IP address because different accounts of the same app or even official app get blocked as well.

**Comment by cdmicacc** [comment]
Our systems use a number of measures that are designed to protect against malicious attackers.  Unfortunately, it sounds like your app is running afoul of one or more of these measures.  You should discourage your users from unfavouriting too many photos too quickly.
