### ISSUE TITLE
get photos not working "include_states" with different image sizes

### ISSUE THREAD

**Issue by gevariya-ajit** [500px/api-documentation#133]
Android specific...
URL: https://api.500px.com/v1/photos?feature=popular&consumer_key=*****&image_size[]=1&image_size[]=2&image_size[]=3&image_size[]=4&include_states=1&only=Abstract&rpp=50&page=1

Not getting favorited and liked in response.

BUT
URL: https://api.500px.com/v1/photos?feature=popular&consumer_key=*****&include_states=1&only=Abstract&rpp=50&page=1

It gives proper response with favorited and liked..
so my signing working properly.

FYI: in android HTTP handle headers internally

Any help would be appreciated. Thanks :)

**Comment by cdmicacc** [comment]
You need to make a request as an authenticated user (ie, using OAuth, not using just a `consumer_key`) to get the liked and favorited states.

**Comment by gevariya-ajit** [comment]
Sign is only happening after authentication, don't you even know?? 

why closing the issue????

**Comment by vachi** [comment]
SO, what was a rude answer? Jeez....

**Comment by cdmicacc** [comment]
@gevariya-ajit I'm afraid I don't understand your issue.  Are you saying you're having trouble authenticating?  The only difference between the two requests you gave appears to be the presence/absence of the `image_size` arguments, which will not affect whether you see the liked/favorited states in the response.  

Am I missing something here?

**Comment by gevariya-ajit** [comment]
We already did request with sign so already authenticated... just two things not working parallel. "image sizes" and "include_states" to gather.

You can see the problem after check above link difference... or at least read the question properly. 

And answer is just requite authentication??? i am already provide authenticated request that is described in my question...

Getting "include_states" is favorited details correct but not in special case with all image sizes request too at the same time.

**Comment by cdmicacc** [comment]
When I make this request:
https://api.500px.com/v1/photos?feature=popular&consumer_key=*****&image_size[]=1&image_size[]=2&image_size[]=3&image_size[]=4&include_states=1&only=Abstract&rpp=50&page=1

using a valid OAuth signature and access key, I get the requested states (see below).  You need to sign  and include the `Authorization` header in every request to the API (not just the first request).  Can you make sure you're doing that (and that you see the `Authorization` header in the HTTP request your code is making)?

```json
{
  "current_page": 1,
  "total_pages": 5,
  "total_items": 211,
  "photos":  [
     {
      "id": 107534223,
      "user_id": 482747,
      "name": "Evanescence",
      "description": "Daisies in the wind",
      "camera": "Canon EOS 50D",
      "lens": "EF24-105mm f/4L IS USM",
      "focal_length": "32",
      "iso": "100",
      "shutter_speed": "",
      "aperture": "",
      "times_viewed": 3854,
      "rating": 98.9,
      "status": 1,
      "created_at": "2015-05-04T13:17:56-04:00",
      "category": 10,
      "location": null,
      "latitude": null,
      "longitude": null,
      "taken_at": null,
      "hi_res_uploaded": 0,
      "for_sale": false,
      "width": 3761,
      "height": 2523,
      "votes_count": 355,
      "favorites_count": 173,
      "comments_count": 40,
      "nsfw": false,
      "sales_count": 0,
      "for_sale_date": null,
      "highest_rating": 98.9,
      "highest_rating_date": "2015-05-05T09:11:22-04:00",
      "license_type": 0,
      "converted": 27,
      "collections_count": 0,
      "crop_version": 9,
      "privacy": false,
      "image_url":  [
        "https://drscdn.500px.org/photo/107534223/w%3D70_h%3D70/47e74f2acfb03af2905a30ae232af715?v=9",
        "https://drscdn.500px.org/photo/107534223/w%3D140_h%3D140/eb54df02139d1c16fe3bce0f8b06147e?v=9",
        "https://drscdn.500px.org/photo/107534223/w%3D280_h%3D280/620147c419bd9c48f556ae19e7492603?v=9",
        "https://drscdn.500px.org/photo/107534223/m%3D900_k%3D1_a%3D1/721df9a2584b5c0bd547b766f4d0e15d"
      ],
      "images":  [
         {
          "size": 1,
          "url": "https://drscdn.500px.org/photo/107534223/w%3D70_h%3D70/47e74f2acfb03af2905a30ae232af715?v=9",
          "https_url": "https://drscdn.500px.org/photo/107534223/w%3D70_h%3D70/47e74f2acfb03af2905a30ae232af715?v=9",
          "format": "jpeg"
        },
         {
          "size": 2,
          "url": "https://drscdn.500px.org/photo/107534223/w%3D140_h%3D140/eb54df02139d1c16fe3bce0f8b06147e?v=9",
          "https_url": "https://drscdn.500px.org/photo/107534223/w%3D140_h%3D140/eb54df02139d1c16fe3bce0f8b06147e?v=9",
          "format": "jpeg"
        },
         {
          "size": 3,
          "url": "https://drscdn.500px.org/photo/107534223/w%3D280_h%3D280/620147c419bd9c48f556ae19e7492603?v=9",
          "https_url": "https://drscdn.500px.org/photo/107534223/w%3D280_h%3D280/620147c419bd9c48f556ae19e7492603?v=9",
          "format": "jpeg"
        },
         {
          "size": 4,
          "url": "https://drscdn.500px.org/photo/107534223/m%3D900_k%3D1_a%3D1/721df9a2584b5c0bd547b766f4d0e15d",
          "https_url": "https://drscdn.500px.org/photo/107534223/m%3D900_k%3D1_a%3D1/721df9a2584b5c0bd547b766f4d0e15d",
          "format": "jpeg"
        }
      ],
      "url": "/photo/107534223/evanescence-by-tramont_ana",
      "positive_votes_count": 355,
      "converted_bits": 27,
      "voted": false,
      "liked": false,
      "disliked": false,
      "favorited": false,
      "purchased": false,
      "image_format": "jpeg",
      "user":  {
        "id": 482747,
        "username": "Tramont_ana",
        "firstname": "",
        "lastname": "",
        "city": "Santander",
        "country": "España",
        "usertype": 0,
        "fullname": "Tramont_ana",
        "userpic_url": "https://pacdn.500px.org/482747/3cdd934d026c892d9ffe89010e59e6db6a7b7157/1.jpg?2",
        "userpic_https_url": "https://pacdn.500px.org/482747/3cdd934d026c892d9ffe89010e59e6db6a7b7157/1.jpg?2",
        "cover_url": null,
        "upgrade_status": 2,
        "store_on": true,
        "affection": 161531
      }
    }
```

**Comment by gevariya-ajit** [comment]
@cdmicacc yeah now both links are working fine with apigee(it wasn't before).

But still my sign/authorization  is not working. even tried with your sample code.
https://github.com/500px/500px-android-sdk

Not getting "favorited" and "likes"....

Do we need to any permission??

HEADER by your sample code: 
Authorization 
OAuth oauth_token="7QcSTg6Rq6YeavpS8CTZdeauVVGFcLEyCdyVP19L", oauth_consumer_key="VAZxcVNP1imDySSHfjOFDvF7vHNFUztLn49yaJIF", oauth_version="1.0", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1430842051", oauth_nonce="-6155427721681578314", oauth_signature="Hjid9gX%2BtrzFKgxZFAMOkqQjbHY%3D"

Thanks for replay :)
