### ISSUE TITLE
license_type in the HTML header

### ISSUE THREAD

**Issue by lindenb** [500px/api-documentation#135]
( posted after https://twitter.com/yokofakun/status/593811589456867328 )

Hi 500px, I want to know what kind of creative common license if used for a given picture .

This information is currently _not_ displayed in the HTML pages. (e.g https://500px.com/photo/78475237/201407132000-by-pierre-lindenbaum )

But there is a license_info in the HTML `header/script`

```json
"license_type":2,
```

can I safely use this (key/value) in the HTML and https://github.com/500px/api-documentation/blob/60d0526d2aba09be56fb55aec73989a81b1e3188/basics/formats_and_terms.md#license-types to get the license information  ?

thanks.

**Comment by cdmicacc** [comment]
Yes, that is the intended use for this value (and yes, the 500px site currently doesn't display this value).
