### ISSUE TITLE
Is search API returning photos from Library?

### ISSUE THREAD

**Issue by tarmo888** [500px/api-documentation#138]
I am new and I thought that Library is private and Profile is public, but when I do a "geo=59.4329269,24.7611928,0.4km" search query with just comsumer key auth then I find this picture
https://500px.com/photo/107385963/smoggy-tallinn-by-teemu-v%C3%A4is%C3%A4nen

But if I go to his profile https://500px.com/uolevi then I get "Teemu hasn't uploaded a photo.". Did he deleted his photo from Profile and it's some syncing issue? Or how is it possible that search API is returning photos that are not on his Profile?

**Comment by pwyliu** [comment]
Hi there,

This user has made this photo available for licensing on 500px Prime, but they haven't put it on their 
public profile. You can find licensable photos in search, but they won't show up in a profile unless selected to.

**Comment by tarmo888** [comment]
Thanks, makes sense.
