### ISSUE TITLE
Search term?

### ISSUE THREAD

**Issue by hubapps** [500px/api-documentation#139]
In the iOS kit, there's a "term" argument, but I find no mention of a search term parameter in the documentation here on github.  Is this a case of me overlooking the correct documentation?  Or does this not exist?  Requests submitted with term return no results (as far as I've been able to determine).

**Comment by omikronn** [comment]
Hello @hubapps, yes the `/photos/search` endpoint supports searching via a `term`. E.g.: `https://api.500px.com/v1/photos/search?term=car`. Does this answer your question?

**Comment by hubapps** [comment]
Using escaped search phrases does not seem to work, such as "term=blue%20car".  Maybe this is supposed to be "blue+car"?  Thank you for confirming that this is a supported endpoint parameter.

**Comment by omikronn** [comment]
@hubapps no problem. Also, you guessed it, that's exactly how you should call the endpoint for search phrases. (e.g. `https://api.500px.com/v1/photos/search?term=red+car`).
