### ISSUE TITLE
licensing_status not changing results

### ISSUE THREAD

**Issue by vachi** [500px/api-documentation#143]
We were told to use the licensing_status param on /photos/search, specifically &licensing_status=3,5 
To aggregate only sellable images, however the param does not make a diff on our API call. 
Do I have the param correct. Our contact Nuno is on vaca.
Any help is much appreciated.

**Comment by cdmicacc** [comment]
Hi vachi,

I checked the search code and it looks like the correct name for the parameter is `licensing_statuses` (rather than `licensing_status`).  Can you try using that name and let me know if it works?

**Comment by vachi** [comment]
Thank You sir worked like a charm.
