### ISSUE TITLE
Image search additional variables

### ISSUE THREAD

**Issue by TMoska** [500px/api-documentation#145]
Hey, I am using your API for image searching (search/image), and would like to receive more information variables about images in a response. How could I receive additional information about :
+ height of an image size 4,
+ width of an image size 4,
+ price of an image if it's on sale ?

**Comment by vachi** [comment]
3. price is set at three levels
Products for Resale  $750
Print Ready RF  $250
Web Ready RF  $50

2. size 4 is 900px on the widest side, so you can calculate the other side by knowing the ratio by taking the original w/h

am I wrong guys?

**Comment by TMoska** [comment]
That is very correct. Thanks for such a quick response !
