### ISSUE TITLE
Get tags of a photo ?

### ISSUE THREAD

**Issue by cmwalolo** [500px/api-documentation#149]
Isn't there a  GET  photos/:id/tags missing in the documentation ? 
I don't find the tags anywhere... But there is a POST and a DELETE tags. 
Can we get the documentation up to dated ? :)

**Comment by machx0r** [comment]
I see two options here, both require adding the "tags=1" parameter to your request:

[`GET photos`](https://github.com/500px/api-documentation/blob/master/endpoints/photo/GET_photos.md)
[`GET photos/:id`](https://github.com/500px/api-documentation/blob/master/endpoints/photo/GET_photos_id.md)

**Note:** I haven't actually tried either of these calls with the parameter

**Comment by pwyliu** [comment]
@machx0r is right, adding `&tags=1` to your request will return tags.
