### ISSUE TITLE
How do we know a photo is on the Profile (public ?) page ?

### ISSUE THREAD

**Issue by cmwalolo** [500px/api-documentation#150]
I don't find the information, that tells me a picture is on the profile page or not. 
On 500px we have two default collections : All Pictures, and pictures on profile page.
And then we have all sets. 

Is the "privacy" field the one to be used ? 

Thanks :=)

**Comment by pwyliu** [comment]
Hi, 

Yes, you guessed right, the `privacy` field will tell you if a photo is on a profile or not. When `true` it means that a photo is on someone's profile (in the Photos tab). When `false` it is not.

Perhaps somewhat confusingly, a photo can have `privacy: true` but still be publicly viewable. This will be the case if the photo is in a public set, but not marked as "Public" in the photo manager. In that case the photo does not appear under the Photos tab, but does appear in the Sets tab of a profile.

If you are curious about our API, I highly recommend you check out our console on [Apigee](https://apigee.com/providers). You can mess around with different endpoints and easily inspect the response in your browser.
