### ISSUE TITLE
DELETE photos/:id/favorite - a limit ?

### ISSUE THREAD

**Issue by Cmejia** [500px/api-documentation#155]
Hello, 

Our app (PhotoStackr) allows users to view favorites in a thumbnail stream. We support batch operations.  One of them is to remove photos from their favorites. So a user can select 1 or 20 or 100 ! photos and say "I want to remove these from my favorites list". 

So we end up sending a DELETE photos/:id/favorite  for each, in relative quick succession. 

As I was testing this (with 7 photos), it seems my IP address got 'blocked' somehow. The delete requests seemed to have gone through, but now any request coming from my public IP tp 500px.com seems to timeout (including web browser, and your own official app).   

How do I know it was my public ip ?
1) I tried with my phone, via LTE only all good
2) Connected to a VPN, and tried connected through there to 500px. It all went well until I tried the delete in batch operation again

So the questions are :
1) Is this blocking of IP intentional or is non-intended ?
2) Do I have to separate the delete requests then ?

**Comment by cdmicacc** [comment]
The favorites API has been deprecated. Please take a look at the new [Galleries APIs](https://github.com/500px/api-documentation#gallery-resources), instead.
