### ISSUE TITLE
[Feature Inquiry] GET random image?

### ISSUE THREAD

**Issue by cassidoo** [500px/api-documentation#156]
Is it possible to get a random image using the `/photos` endpoint (or any of the others)?

**Comment by Dinchy87** [comment]
I know its almost 2 years after the question but you could code it yourself. The API gives back how many pages and pictures the response has, i would just do a random int and use this as the picture in the collection of all pictures. There is just something to consider, and this are the pages, so i would add two random values and check if both are ok, i mean page 20 and picture 10 if there is a picture on this position but it should be. With the API directly there is no way but its just a few lines of code to code yourself.

**Comment by cassidoo** [comment]
Heh, this was a long time ago, but thanks @Dinchy87 for the response. 👍 I think I ended up doing something similar to that plus Imgur's random API for a variety of images. I'll close this now.
