### ISSUE TITLE
Collections API

### ISSUE THREAD

**Issue by sayontan** [500px/api-documentation#17]
Hello,
500px.com's collections API today works in a very odd manner. It requires authentication, but it only displays the authenticated user's collections. This seems counter-intuitive: if I put in a login button on my website, and a visitor logs in using that, he/she will see his/her collections, not my collections. Ideally I should be able to show all collections for a particular user on my site by putting in a "user_id" parameter, but that doesn't work.

Based on one of my previous posts here (https://github.com/500px/api-documentation/issues/6) I believe that a rewrite is planned for the collections API. Is there an ETA on this? Will there be any changes to how the collections work?

**Comment by davidrusu** [comment]
See galleries API, see: https://github.com/500px/api-documentation/tree/master/endpoints/galleries
