### ISSUE TITLE
Can't get PUT users/:user_id/galleries/:id/items to work

### ISSUE THREAD

**Issue by HayoBaan** [500px/api-documentation#170]
I'm enhancing our software to also allow users to choose the gallery their just uploaded image should be placed in. But somehow I can't get this to work. The response of the server is always 200 OK, but not with the expected result in the JSON; this is always completely empty instead of showing me what was done.
Here's what I have as the data for the PUT:
URL: users/xxxx/galleries/xxxx/items
PARAMS: {{"add":{"photos":[xxxx]}}: }
HEADERS: {Authorization: OAuth oauth_callback="https%3A%2F%2Fxxxxxx, oauth_consumer_key="xxxxx", oauth_nonce="xxxx", oauth_signature="xxxx", oauth_signature_method="HMAC-SHA1", oauth_timestamp="xxxx", oauth_token="xxxx", oauth_version="1.0"}

What am I doing wrong here?
Note: the 500px console does not yet support the Gallery endpoints so I can't test there.

**Comment by cdmicacc** [comment]
This API expects a JSON body -- from your description it doesn't look like you're passing one (at least, you're not setting `Content-Type: application/json`).

**Comment by HayoBaan** [comment]
Awesome! It was really that simple…

Thanks,
Hayo
