### ISSUE TITLE
New/Featured/Trending Galleries API 

### ISSUE THREAD

**Issue by abubberman** [500px/api-documentation#171]
Hi,

is it possible to fetch the new, featured and trending galleries using the API? 
I've seen the API calls that require a userId to fetch the galleries, but it would be great if I could create a page where all the galleries are shown.

**Comment by cdmicacc** [comment]
At this time there isn't an API to get a list of trending/featured/new galleries.  However, we're continuing to evolve the new Galleries API, and if/when such an API is made public we'll make sure to let you know!

**Comment by abubberman** [comment]
Thnx for the response. Is it possible to use the size parameters for the photos in the gallery? It would be great to have thumbnail photos for an overview, and full size photos for more details.

**Comment by cdmicacc** [comment]
Yes, but it looked like the docs were missing that parameter.  You can set `include_cover=1` and also `cover_size` to set the image size for the cover to get the cover photo for the galleries.

**Comment by abubberman** [comment]
Thanks for the information. Is it also possible to provide an image size for the collection of photos in the gallery?

**Comment by cdmicacc** [comment]
Yes, via the standard `image_size` parameter.
