### ISSUE TITLE
API not returning 500px upload_limit_expiry with correct date

### ISSUE THREAD

**Issue by NewPProd** [500px/api-documentation#177]
I've been using the 500px API for quite a while and think there is a problem with the user field for "upload_limit_expiry".

When I use GET https://api.500px.com/v1/users the returned JSON response always seem to have "upload_limit_expiry" as being the current date time.
According to the docs, it should contain the "date and time of the beginning of the new upload limit cycle, datetime".

Every time I run the call for GET https://api.500px.com/v1/users I get a different value in the "upload_limit_expiry" field - and the value always seems to be the current date time.

I can reproduce this every time in using the 500px API console (http://bitly.com/api500px).

Could you confirm this is a bug in the 500px API and if so could you kindly consider fixing it?

Here is an extract from your 500px API console. You can see the "upload_limit_expiry" in the response matching the date time that the call was made in the header (obviously with the timezone difference applied).

HTTP/1.1 200 OK
X-Runtime:
0.051628
Status:
200 OK
ETag:
"9554251ac02f74fba0e9c7432525d1e2"
Transfer-Encoding:
chunked
Date:
Wed, 13 Jan 2016 16:45:58 GMT
X-UA-Compatible:
IE=Edge,chrome=1
Set-Cookie:
_hpx1=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiJWM3OTA2OGFkZWUxZmI3N2RlNDg1N2EwNzAxODE0NjU2BjsAVEkiCWhvc3QGOwBGIhJhcGkuNTAwcHguY29tSSIZd2FyZGVuLnVzZXIudXNlci5rZXkGOwBUWwdbBmkDbeCKSSIZRFN5bTlkem9NQzVvb1lKRDVqOFkGOwBU--4666e43017696af0272b4720b4aec15c4263e1ba; domain=.500px.com; path=/; HttpOnly
X-Request-Id:
b4340eb3069270b48a76963607aad7e4
X-Rack-Cache:
miss
Connection:
keep-alive
Content-Type:
application/json; charset=utf-8
Server:
api2
Cache-Control:
must-revalidate, private, max-age=0

{
  "user":  {
    "id": xxx,
    "username": "xxxxx",
    "firstname": "xxx",
    "lastname": "xxx",
    "birthday": null,
    "sex": null,
    "city": null,
    "state": null,
    "country": null,
    "registration_date": "2014-07-30T12:43:30-04:00",
    "about": null,
    "usertype": 0,
    "domain": "xxx.500px.com",
    "fotomoto_on": false,
    "locale": "en",
    "show_nude": false,
    "allow_sale_requests": 1,
    "fullname": "xxx xxx",
    "userpic_url": "https://secure.gravatar.com/avatar/b73ad3b5f7847df5e425a1870aafb3bd?s=300&r=g&d=https://pacdn.500px.org/userpic.png",
    "userpic_https_url": "https://secure.gravatar.com/avatar/b73ad3b5f7847df5e425a1870aafb3bd?s=300&r=g&d=https://pacdn.500px.org/userpic.png",
    "cover_url": null,
    "upgrade_status": 0,
    "store_on": false,
    "photos_count": 41,
    "galleries_count": 10,
    "affection": 30,
    "in_favorites_count": 3,
    "friends_count": 0,
    "followers_count": 0,
    "analytics_code": null,
    "invite_pending": false,
    "invite_accepted": false,
    "email": "xxx@xxx.com",
    "upload_limit": 16,
    "upload_limit_expiry": "2016-01-13T11:45:57-05:00",

**Comment by Melraidin** [comment]
If the isn't currently at their upload limit then the current time is returned. If the user is at their upload limit then the time that they'll next be able to upload is returned.

**Comment by NewPProd** [comment]
OK - good information. Could you please update the docs to include this to help other people?
Thanks.

**Comment by Melraidin** [comment]
Sorry, yes, have just done so. Thanks for letting us know about this.

**Comment by NewPProd** [comment]
Great - thanks.
