### ISSUE TITLE
Cannot send comment with special characters 

### ISSUE THREAD

**Issue by abubberman** [500px/api-documentation#180]
Hi,

I've got some problems posting comments which contain special characters like ! and ?
I'm using the API in a C# project and sending comments is working fine when sending only text. 

In my C# project I use the UrlEncode method from the UrlEncoder class, which seems to create a correctly encoded text. But when i post the request, the encoded text is also saved as the encoded text.

So for example when i post the text: Comment!?
Then my request URL will become: https://api.500px.com/v1/photos/128238823/comments?body=Comment!%3F

When i use this url in the API console, everything is working fine. But when i send the request from my code, the saved comment is Comment!%3F, instead of Comment!?

Any idea what i'm doing wrong?

**Comment by HayoBaan** [comment]
Looks  like you are doubly encoding your text. Add a line of debug code to show what text you are actually sending.

**Comment by abubberman** [comment]
Ive just sent another request with the following text: Another one!?

The request that is sent was:
https://api.500px.com/v1/photos/128238823/comments?body=Another%2520one!%253F

But this time i received an unauthorized exception.This also occurs for the request i've posted earlier.
https://api.500px.com/v1/photos/128238823/comments?body=%20Comment!%3F

When i remove the code that encodes the parameter, i also receive the same response.

**Comment by abubberman** [comment]
I've found the issue. I was indeed doing some things wrong when encoding. I needed to encode the strings to make sure special characters are processed correctly. But I also had some encoding for creating proper requests. So the encoded value got encoded again.

Problem solved now!
