### ISSUE TITLE
Include gallery ids in photo requests

### ISSUE THREAD

**Issue by abubberman** [500px/api-documentation#181]
Hi,

Is it possible to include the gallery ids in the photo requests?
I want to add a dialog to my app in which i can select a gallery.
But I also need to know if the current photo is already in that gallery.

![image](https://cloud.githubusercontent.com/assets/13328911/12646907/05fbb94c-c5d3-11e5-96b6-962c9dafa5e9.png)

**Comment by abubberman** [comment]
I saw that it is possible to retrieve the galleries by requesting the following url: 
https://api.500px.com/v1/photos/136079727/galleries/

This will return a list of galleries in which the photo is included. But there could be many pages with galleries, 

Is there any way to return only the galleries of the logged in user in which the photo is included?

**Comment by moc426** [comment]
I am interested in this as well, how can we identify which current user galleries an image belongs to?

**Comment by moc426** [comment]
hey @abubberman 

I figured it out, use https://api.500px.com/v1/photos/136079727/galleries/ and pass user_id parameter with userid and it will return only those of the user.

**Comment by abubberman** [comment]
Thanks for sharing.  Will try this tomorrow.

**Comment by abubberman** [comment]
It's working. Much faster like this :-)
