### ISSUE TITLE
Error from PUT /v1/users/xxx/galleries/yyy/items

### ISSUE THREAD

**Issue by NewPProd** [500px/api-documentation#182]
Hi,

I've been notified of a few errors when using:
PUT /v1/users/xxx/galleries/yyy/items
The error is:
{"error":"Invalid photo ID","status":400}

This error does not entirely align with what is documented as the range of errors (here's a copy and paste from the doc):
400 Bad Request — The request issued is missing one or more of the required parameters or contains parameters in an invalid form.
403 Forbidden — The gallery is not owned by you.
403 Forbidden — The photo was either deleted, is private, or belongs to a deactivated user.
404 Not Found — The gallery you are requesting does not exist.
404 Not Found — A photo you tried to add does not exist.

The error received is by a customer, and is not reproducible by me. I cannot see a reason why the photo ID is incorrect. The ID is from a photo that was uploaded only seconds earlier.
The error code number indicates a missing parameter.
The error text message indicates the photo does not exist.
And I'm not sure either is actually the problem.
1. Could you kindly improve the error details to remove the ambiguity?
2. Could you comment on what may cause this error - I cannot reproduce it - so are there situations where a recently uploaded photo may not be ready to be linked to a gallery?

Thanks,
Rob

**Comment by Melraidin** [comment]
Thanks for the detailed report Rob. We'll take a look at this and update you here.

**Comment by djole103** [comment]
@NewPProd Thanks for your help Rob, the issue has been fixed.

**Comment by NewPProd** [comment]
OK - thanks.

**Comment by Fanshia** [comment]
The same error appeared to me. With photo_id = 1008751935
