### ISSUE TITLE
API returns users that don't exist on the site.

### ISSUE THREAD

**Issue by ivandotv** [500px/api-documentation#188]
If I search for user **ivan** I get back that user. I can also get the images of the user. 
In **ivan** case I get back 8 images.
However user **ivan** doesn't exists on 500px website.
https://www.500px.com/ivan

**Comment by creature** [comment]
Hi Ivan! Thanks for the bug report. We've fixed this for `GET /v1/users/show`, and will try to also fix it for `GET /v1/photos` soon too. :)
