### ISSUE TITLE
GET photos/search endpoint. Add "feature" parameter

### ISSUE THREAD

**Issue by ORuban** [500px/api-documentation#190]
Please provide `feature` parameter for `photos/search` endpoint - the same as you already have for `photos` endpoint:
`feature  — Photo stream to be retrieved.`

**Comment by mck182** [comment]
Hey there,

search has a `was_featured_type` parameter where
you can specify which feature you want to search.

This is currently missing from our documentation,
I'll add it shortly.

Martin, 500px
