### ISSUE TITLE
Storing images for more than 24h

### ISSUE THREAD

**Issue by marsh12th** [500px/api-documentation#202]
This may sound silly but it's acutally quite important.
The API Terms of Use read

> You shall not: Cache or store any photos or images obtained from the 500px site for more than 24 hours.

Does this include also images taken from the 500px API ?
Since they are watermarked anyways...

Thanks

**Comment by mck182** [comment]
Hey there,

thanks for getting in touch! That is correct, it includes any and all content obtained from 500px in any way.

We've also updated the wording of that section. Hope that helps!

Best wishes,
Martin, 500px

**Comment by marsh12th** [comment]
Yeah ty
