### ISSUE TITLE
return photos with username

### ISSUE THREAD

**Issue by hassantafreshi** [500px/api-documentation#207]
before said anythings, sorry for my bad English.

I want to get images by filtering by username. i read document and try below API but didn't return valid value.
 for example : i want get Photos  added by this username "nastyafresh" 
https://api.500px.com/v1/photos?username=nastyafresh&image_size=2&consumer_key=XXXXXX

**Comment by marsh12th** [comment]
You're missing the 'feature'
This should be your link

https://api.500px.com/v1/photos?feature=user&username=nastyafresh&image_size=2&consumer_key=XXXXXX

**Comment by hassantafreshi** [comment]
Thanks for your useful answer .
