### ISSUE TITLE
Allow different size of cover photo

### ISSUE THREAD

**Issue by ScottIsAFool** [500px/api-documentation#209]
Because some cover photos can be massive, it would be nice if we could be a bit more restrictive over what size image we want to pull down. This will be especially useful on mobile devices where we may only need to use a smaller image.

**Comment by mck182** [comment]
Hey Scott,

sorry for the late response, generally the cover
images for profiles that the API will return will
already be scaled down to not be massive.

Hope that helps!

Best wishes,
Martin from 500px
