### ISSUE TITLE
API response is very slow

### ISSUE THREAD

**Issue by JamesJGoodwin** [500px/api-documentation#213]
The API response is very slow. It tooks about 1-2 seconds to parse info about only 1 image.

**Comment by mck182** [comment]
Hi James,

thanks for letting us know. We're constantly trying
to improve our infrastructure and our latest testing
shows that the response times are now way under
a second. Your slowness may have also been caused
by a possible site maintenance that was going on
during that time.

Best wishes,
Martin from 500px
