### ISSUE TITLE
Can I use something to get my photos without being authorized

### ISSUE THREAD

**Issue by syabro** [500px/api-documentation#215]
I want to integrate photos from 500px to the gallery on my website.
Is it possible to do it without authorizing?

I don't need anything fancy, just something like /user/photos/gallery/ to get photos from there.

**Comment by mck182** [comment]
Hey Maxim,

you certainly can! Have a look at the documentation
for the `/photos` endpoint, all you need is a valid
consumer key. Follow the main README here to find
out how to do that.

The aforementioned `/photos` endpoint:

https://github.com/500px/api-documentation/blob/master/endpoints/photo/GET_photos.md

Best wishes,
Martin from 500px
