### ISSUE TITLE
500px API Endpoint Status

### ISSUE THREAD

**Issue by sanik90** [500px/api-documentation#221]
it seems that https://api.500px.com/v1/ endpoints is down and redirected to https://**api2**.500px.com/v1/, notice the api2, but the status on status.500px.com is **Operational**, did anyone else came across this?

**Comment by jpvalery** [comment]
Yes I did - thought this was an issue on my end. Glad I'm not the only one.

**Comment by josemlechon** [comment]
I'm getting nuts with this problem trying to connect with a mobile app. I also have problems to access to picture on 500px website.  

BTW, the API console works perfectly.

**Comment by makramkd** [comment]
Sorry guys, we recently made a DNS change that went really bad. Things should be fine now since we reverted. The TTL on that particular entry was unusually long and it should have expired by now.

**Comment by jpvalery** [comment]
Working back now apparently

**Comment by makramkd** [comment]
It should be working now. Closing this.
