### ISSUE TITLE
500px Integration Module (Plugin) for Drupal 8

### ISSUE THREAD

**Issue by dakkusingh** [500px/api-documentation#223]
Hi All,
If there are any lovers of 500px and Drupal, it might be worth knowing that there is a module I have been working on since 2013 and recently I was able to upgrade this to Drupal 8.

Give it a try and looking forward to your feedback 👍 

Code at: 
https://github.com/dakkusingh/drupal500pxintegration
feedback and collaboration welcome 

Official project page is at:
https://www.drupal.org/project/d500px

**Comment by mck182** [comment]
Hey there,

thanks a lot for letting us know, this is great!
Just a note that the official project page is
using the old logo, you might want to update
that one :) You can obtain it from this page:
https://about.500px.com/press/#brand

Given your project is also hosted on Github
with its own issues tracker, I'll close this issue
here as it's unrelated to the actual API docs
project of this repo.

Best wishes,
Martin from 500px

**Comment by dakkusingh** [comment]
Hi @mck182 am I right in understanding that 500px API is now shut down?
