### ISSUE TITLE
Can add "voted" field in photos?

### ISSUE THREAD

**Issue by 0xdatou** [500px/api-documentation#226]
I found that there is no voted field in response json of [Get Photos](https://github.com/500px/api-documentation/blob/master/endpoints/photo/POST_photos.md)

It's very embarrassed😥

Is it possible add "voted" field to photos feed?

**Comment by moc426** [comment]
https://github.com/500px/api-documentation/blob/master/endpoints/photo/GET_photos.md

You linked post photo. This  link is for get photos 

"include_states — If set to 1, returns state of the photo for the currently logged in user and authenticated request.

Returned values:

'liked' — Boolean value whether the current user has liked this photo
'purchased' — Boolean value whether the current user has bought this photo"
