### ISSUE TITLE
Documentation for uploading photos is unclear

### ISSUE THREAD

**Issue by mardy** [500px/api-documentation#249]
Hi!
  I understand that the first step in order to upload a photo is to call `POST photos`, and that will return both an upload key and a "presigned post". Unfortunately the documentation doesn't tell how to proceed then. The [upload_key](https://github.com/500px/api-documentation/blob/master/authentication/upload_key.md) page is also very confusing, because it says that some parameters are required, but then the list of accepted parameters is empty. Moreover, it returns the OAuth consumer key and access key (but it said that I need them in order to call this method!), without telling what one should do with them.

Can you please clarify? :-)

**Comment by mck182** [comment]
Hey Alberto!

If I understand it correctly, the sequence is as follows:

```POST /photos```

...you get back the photo structure including the `presigned_post`
object. At this point, you can ignore the `upload_key` which is for
legacy uploads.

The `presigned_post` will give you the url for the second request:

```POST presigned_post['url']```

...where the body of the request are the fields that are part of the
`presigned_post` structure, followed by the file in `file`, like this:

```
{
       "key": "...",
       "x-amz-meta-user_id": "0000",
       "x-amz-signature": "...",
       "x-amz-algorithm": "...",
       "x-amz-credential": "...",
       "x-amz-date": "20120608131704Z"
       "file": ...the file...
}
```

Let me know if that doesn't work! :)

Cheers,
Martin

**Comment by mardy** [comment]
Thanks @mck182 ! That indeed makes sense.
I've now tried an upload: the first part works well: I get a presigned_post object filled with interesting stuff, which I use for the S3 upload. That returns a status code of 204 (which according to the documentation means that the upload went successfully) and empty body, but when I go to the 500px website, I cannot find the uploaded photo (actually, I still have 0 photos :-) ).

When posting to the `photos` endpoint I do set `auto_activate` to `"true"` (as a string). Am I missing one last step?

**Comment by mck182** [comment]
Thanks, I'll ask the platform guys.

Btw. what's your 500px username?

Cheers,
Martin

**Comment by mardy** [comment]
It's `info9503` :-)

**Comment by mardy** [comment]
By the way, I see that my upload limit has decreased by two; indeed I made 2 attempts to upload photos.

**Comment by mck182** [comment]
Hey,

we've looked at your profile and the photos are
there, they are just not public. Can you share
the full list of parameters for both requests?

Cheers,
Martin

**Comment by mardy** [comment]
Hi Martin,
  I used these parameters:

- `name`: don't remember
- `description`: don't remember
- `tags`: don't remember
- `category`: `0`
- `auto_activate`: `"true"`

When I say "don't remember", it means that I don't remember which value I passed, but I'm sure that the field was passed (might be with an empty value, though).

But how is it possible that I myself can't see the photos? I'm logged into the site, so I guess I should be able to see my private photos.

**Comment by mck182** [comment]
Hey,

you can, navigate to your profile icon top right ->Manage Photos
-> All photos in the left sidebar. As to why are they private,
I'm not sure. You can try passing `privacy=0` to the first `POST`
request, that should force it to not be private.

Cheers,
Martin

**Comment by mardy** [comment]
Ah! Indeed, they are there :-) I'll try with the `privacy` parameter, thanks!

**Comment by mardy** [comment]
I can confirm that `privacy=0` helps. I guess this should also be documented (or maybe this should be the default value).

**Comment by mck182** [comment]
Hey,

I've rewritten the docs for uploading a file. Should now
be much more clearer :)

https://github.com/500px/api-documentation/blob/master/basics/upload.md

Cheers,
Maritn
