### ISSUE TITLE
Download bigger resolution images if you are the owner

### ISSUE THREAD

**Issue by jeremysom** [500px/api-documentation#29]
As a photographer/developer I'd love to be able to have my photos stored on 500px accessible via the api at a higher resolution than is currently available. The idea behind this is to be able to use said images on a retina iPad screen in order to showcase my work.

So the larger resolutions would be available to you only if you are the one who uploaded them. I'd like to make an iPad app designed specifically for photographers with the ability to showcase their work on their iPads (me included). In an ideal world, I'd like to be able to get a resolution of 2048 along the long edge of a photo, however I understand the problems with bandwidth and storage this would perhaps create. So I understand if that's not possible, but any more resolution then we have currently would be great. This way, a photo could simply be uploaded to 500px and then the images on the photographer's iPad would be updated with their current work to show to clients and whatnot.

**Comment by nakulpathak3** [comment]
Was this ever done? Pls @DeonHua I need this

**Comment by pavelber** [comment]
+1

**Comment by mck182** [comment]
Hey everyone,

thanks for getting in touch, couple notes:
* the API currently does not offer you to download original res photos
* the largest available size is 2048 along the longest edge

[See this page for details on all the available sizes](https://github.com/500px/api-documentation/blob/master/basics/formats_and_terms.md#image-urls-and-image-sizes)

We believe that the current largest size offered by the
API is enough for the purposes of our photos API and
at this point we're not planning to add higher resolutions.

Best wishes
Martin, 500px
