### ISSUE TITLE
Get Images by License

### ISSUE THREAD

**Issue by leonkunert** [500px/api-documentation#35]
You already have an indicator showing what license an image has. Would be great to get just images with a certain license.

**Comment by mck182** [comment]
Hey everyone,

for a while we're now accepting `license_type` as
a parameter to the URL, which allows you to specify
the required license. You can read more about that
at the [licenses type section](https://github.com/500px/api-documentation/blob/master/basics/formats_and_terms.md#license-types).

Best wishes
Martin, 500px
