### ISSUE TITLE
Any way to link to 500px.com pages...?

### ISSUE THREAD

**Issue by toyg** [500px/api-documentation#39]
The API is nice and the fact you allow us to get direct URLs to pictures is perfect, but in an ideal world, one of the parameters returned in the main Photo properties would be a URL to the actual page for the photo on 500px.com. After all, we all want to make money for the original photographers and for you, so linkbacks are a must.

At the moment we can hack it together ('http://500px.com/photo/' + id), but it's not very solid -- the minute you change your url scheme ever so slightly, you'll break all the 3rd party apps. It'd be nice to just have a 'mainURL' property with the full address.

**Comment by mck182** [comment]
Hey there,

thanks for the suggestions! I know this answer is a bit
late, but for some time now we've been including this
photo page url in our photo responses, you can find it
under the `url` key. It's still a relative URL and you have
to prepend the `500px.com`, but that part is not likely
to change :)

Best wishes
Martin, 500px
