### ISSUE TITLE
please update the photos.search to include 'nsfw' as a search parameter

### ISSUE THREAD

**Issue by vachi** [500px/api-documentation#45]
i just tested, 
api500px.photos.searchByTerm(searchTem, {'rpp': 20, 'nsfw': false, 'image_size':'1'}, function(err, result) {......
seems to work, should be in a the docs no, [Here](https://github.com/500px/api-documentation/blob/52c72f744fa2c7fb1bfc19abda60e0594b3d6993/endpoints/photo/GET_photos_search.md#parameters)

**Comment by mck182** [comment]
Hey Vache,

thanks for the note, the latest `/photos/search`
supports sending `exclude_nude=1` to exclude
all NSFW photos. This is now added in 
https://github.com/500px/api-documentation/pull/225

Best wishes
Martin, 500px
