### ISSUE TITLE
PUT collections/:id deletes other existing photos

### ISSUE THREAD

**Issue by auth-stack** [500px/api-documentation#47]
Hi,

I am adding a photo to an existing collections, the photos successfully adds to the collection but it deleted other photos inside the collection with only the new photo added remains.

does PUT collections/:id deletes existing photos in the collection or is this a bug?

thanks

**Comment by mck182** [comment]
Hi there,

this is an old issue and we have deprecated collections
in favor of galleries now, which can be found under here:

https://github.com/500px/api-documentation#gallery-resources

Best wishes
Martin, 500px
