### ISSUE TITLE
Get photos api response doesn't include favorited field.

### ISSUE THREAD

**Issue by bipinvaylu** [500px/api-documentation#51]
I am signing api call with signed in user credentials and added url += "&include_states=true"; still not getting Favorited field.
waiting for quick response.

**Comment by gevariya-ajit** [comment]
our auth sign is working fine because if we pass image sizes param then it's not working else giving proper response

**Comment by bipinvaylu** [comment]
@freeatnet If i remove image size parameters then i am getting favorited in api response.
For example: https://api.500px.com/v1/photos?feature=popular&consumer_key=VAZxcVNP1imDySSHfjOFDvF7vHNFUztLn49yaJIF&image_size[]=1&image_size[]=2&image_size[]=3&image_size[]=4&include_states=1&only=Abstract&rpp=50&page=1

Removed: image_size[]=1&image_size[]=2&image_size[]=3&image_size[]=4&

Please help me to figure out this issue.
