### ISSUE TITLE
Add 'favorited_at' date to user's favorite photos json

### ISSUE THREAD

**Issue by rmandvikar** [500px/api-documentation#55]
The GET photos documentation mentions that the user's favorite photos json is sorted by when the photos were added to the favorites. I'd like the 'favorited_at' date, apart from created_at date, included in the json as well.

**Comment by cdmicacc** [comment]
The favorites API has been deprecated. Please take a look at the new [Galleries APIs](https://github.com/500px/api-documentation#gallery-resources), instead.
