### ISSUE TITLE
PHP: photos/upload / Image from URL

### ISSUE THREAD

**Issue by ghost** [500px/api-documentation#81]
Hello, I am using your api with PHP, with this fantastic API integration: https://github.com/jldavid/500px-php/

However, I am stucked on the same point for some time ago.
I have the following code and it's not working:

``` php
$params = array(
        'name' => "Sample name",
        'description' => "Sample description bla bla bla",
        'category' => 18,
        'privacy' => 0,
        'file' => file_get_contents('url for the image')
);
$content  = $connection->post('photos/upload', $params);
```

Probably I am not passing the file on the correct format, because I know it should be multipart/form-data.
Any ideas or documentation about how can I upload a photo?

Thanks

**Comment by gerri80** [comment]
Hi.
I have the same problem here. I'm using the Abraham Williams TwitterOAuth lib und want to upload a photo. But I don't know how to pass the file in the post command.

Did anyone find a solution for this ?

Thanks!

**Comment by zbagadiya** [comment]
Hi,
I want to know list of parameters that can be pass in the get method..As i want to know the detail of user on basis of their userid..Is it possible?
